stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

test:
  stage: test
  image: node:10.15.3-stretch
  script:
    - cd ./products/backend && npm install
  cache:
    key: test-cache
    paths:
      - node_modules/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^WIP.*/i
