version: '3.1'

services:
  insurance-backend:
    container_name: insurance-backend
    image: node:10.15.3-stretch
    tty: true
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    networks:
      - main

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - main

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    volumes:
      - mongo_data:/data/db
    ports:
      - 8081:8081
    networks:
      - main

volumes:
  mongo_data:

networks:
  main:
