version: '3.1'

services:
  insurance-backend:
    container_name: insurance-backend
    image: node:10.15.3-stretch
    tty: true
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    networks:
      - main

networks:
  main:
