version: '3.7'

services:
  dev_insurance-products-fo:
    container_name: dev_insurance-products-fo
    image: node:10.15.3-stretch
    working_dir: /app
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  test_insurance-products-fo:
    container_name: test_insurance-products-fo
    image: node:10.15.3-stretch
    working_dir: /app
    command: npm test
    volumes:
      - ./:/app

networks:
  main_dev:
