version: '3.7'

services:
  dev_insurance-products-fo:
    container_name: dev_insurance-products-fo
    image: node:10.15.3-stretch
    working_dir: /app
    command: npm start
    ports:
      - 8080:8080
    environment:
      BACKEND_URL: ${BO_URL}
    volumes:
      - ./:/app
    networks:
      - main_dev

  test_insurance-products-fo:
    container_name: test_insurance-products-fo
    image: node:10.15.3-stretch
    working_dir: /app
    command: npm test
    volumes:
      - ./:/app
    networks:
      - main_dev


networks:
  main_dev:
